### PR TITLE
Bugfix: Exclude opt

### PR DESCRIPTION
**Pull request by limitusus**
Found a tiny bug when passed string(s) to `-x`, not surrounded by `/`s.

### CODE REVIEW

**Review by wata-gh — APPROVED** [review]
looks good!
thanks!

**Comment by wata-gh** [comment]
I'll fix CI failure in today or tomorrow and merge this PR.

**Comment by limitusus** [comment]
@wata-gh Hi could you release it (even as beta)?

**Comment by wata-gh** [comment]
sorry for the late response...

release as 0.1.5.beta1.

**Pull request merged**
